import {
    autoGeneratedHashKey,
    attribute,
    table
} from '@aws/dynamodb-data-mapper-annotations';

@table('analysis_definitions')
export default class VirusDefinitionModel {
    @autoGeneratedHashKey()
    id?: string;

    @attribute({ defaultProvider: () => new Date() })
    date?: Date;

    @attribute()
    hash?: string;
}