import {
    autoGeneratedHashKey,
    attribute,
    table
} from '@aws/dynamodb-data-mapper-annotations';

@table('analysis_history')
export default class HistoryModel {
    @autoGeneratedHashKey()
    id?: string;

    @attribute({ defaultProvider: () => new Date() })
    date?: Date;

    @attribute()
    hash?: string;

    @attribute()
    filename?: string;

    @attribute()
    result?: boolean;
}